<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SanRestful\Module'                        => __DIR__ . '/Module.php',
    'SanRestful\Controller\SkeletonController' => __DIR__ . '/src/SanRestful/Controller/SkeletonController.php',
    'SanRestfulTest\Framework\TestCase'        => __DIR__ . '/tests/SanRestful/Framework/TestCase.php',
    'SanRestfulTest\SampleTest'                => __DIR__ . '/tests/SanRestful/SampleTest.php',
);
