<?php
$title = 'Add new Customer';
$this->headTitle($title);
?>

<script type="text/javascript">

$(document).ready(function(){
	$('#cancelbutton').click(function(){
		parent.history.back();
		return false;
	});
});



</script>

<div class="row">
    <div class="col-sm-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
            <div class="panel-body">
            
<?php

$form->setAttribute('action', $this->url('agcustomer', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));

?>

<div class="form-group">
<?php echo $this->formRow($form->get('name'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('email'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('phone'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('level'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('status'));?>
</div>

<div class="form-group">
<?php echo $this->formSubmit($form->get('submit'));?>
&nbsp;<?php echo $this->formelement($form->get('cancel'));?>
</div>


<?php 
echo $this->form()->closeTag();

?>

            </div>
        </div>
    </div>
</div>