<?php
$title = 'Add new Cart Item';
$this->headTitle($title);
?>

<style>
<!--
form label, form label span {
 display: block;
}
-->
</style>

<div class="row">

<div class="col-sm-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escapeHtml($dish->name);?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <img src="<?php echo $this->escapeHtml($dish->image)?>" />
                </p>
                <p>
                    <?php echo $this->escapeHtml($dish->price);?>
                </p>
                <p>
                    <?php echo $this->escapeHtml($dish->note);?>
                </p>
            </div>
        </div>
</div>

<div class="col-sm-4" style="background-color:#6495ED">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escapeHtml($title);?></h3>
            </div>
            <div class="panel-body">

<?php

$form->setAttribute('action', $this->url('cartitem', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('cartid'));
echo $this->formHidden($form->get('dishid'));
?>

<div class="form-group">
<?php 
echo $this->formRow($form->get('qty'));?>
</div>
<div class="form-group">
<?php echo $this->formRow($form->get('note'));?>
</div>

<div class="form-group">
<?php echo $this->formSubmit($form->get('submit'));?>
</div>

<?php 
echo $this->form()->closeTag();

?>
        </div>
    </div>        
</div>


</div>