<?php
$title = 'Memberships';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
 <?php foreach ($memberships as $membership) : ?>

     <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escapeHtml($membership->restaurantName);?></h3>
            </div>
            <div class="panel-body" style="height: 200px">
                <p>
                    <img src="<?php echo $this->escapeHtml($membership->rimage)?>" style="width: 200px" />
                </p>
                <p>
                    <?php echo $this->escapeHtml($membership->level);?>
                </p>
                <p>
                    <?php echo $this->escapeHtml($membership->customerName);?>
                </p>
            </div>
        </div>
    </div>

 <?php endforeach; ?>
</div>
