<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Membership\Module'                        => __DIR__ . '/Module.php',
    'Membership\Controller\MembershipController' => __DIR__ . '/src/Membership/Controller/MembershipController.php',
    'MembershipTest\Framework\TestCase'        => __DIR__ . '/tests/Membership/Framework/TestCase.php',
    'MembershipTest\SampleTest'                => __DIR__ . '/tests/Membership/SampleTest.php',
);
