<?php

$title = 'Customers';
$this->headTitle($title);
?>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left" style="padding-top: 7.5px;"><?php echo $this->translate($title) ?></h3>
                <div class="btn-group pull-right">
                    <a class="btn btn-default btn-sm" href="<?php echo $this->url('restcustomer', array('action'=>'add'));?>">Add</a>
                </div>
            </div>
            <div class="panel-body">
            
                 <table class="table">
                 <thead>
                 <tr>
                     <th>Name</th>
                     <th>Email</th>
                     <th>Phone</th>
                     <th>&nbsp;</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php foreach ($customers as $customer) : ?>
                 <tr>
                     <td data-title="Name">
                        <?php echo $this->escapeHtml($customer->name);?>&nbsp;
                     </td>
                     <td style="vertical-align: middle;" data-title="Email"><?php echo $this->escapeHtml($customer->email);?>&nbsp;</td>
                     <td style="vertical-align: middle;" data-title="Phone"><?php echo $this->escapeHtml($customer->phone);?>&nbsp;</td>
                     <td style="vertical-align: middle;" data-title="">
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('restcustomer',
                             array('action'=>'edit', 'id' => $customer->id));?>">Edit</a>
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('restcustomer',
                             array('action'=>'delete', 'id' => $customer->id));?>">Delete</a>
                     </td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>

            </div>
        </div>
    </div>
</div>      