<?php
$title = 'Add new Credit Card';
$this->headTitle($title);
?>

<style>
<!--
form label, form label span {
 display: block;
}
-->
</style>

<div class="row">
<div class="col-sm-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
        <div class="panel-body">
        
<?php

$form->setAttribute('action', $this->url('restcredit', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('tid'));
echo $this->formHidden($form->get('type'));
?>

<div class="form-group">
<?php echo $this->formRow($form->get('number'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('name'));?>
</div>


<table style="width: 100%">
<tr><td>
<div class="form-group">
<?php echo $this->formRow($form->get('month'));?>
</div>
</td>
<td style="text-align: center"> / </td>
<td>

<div class="form-group">
<?php echo $this->formRow($form->get('year'));?>
</div>
</td>
</tr>
</table>

<div class="form-group">
<?php echo $this->formRow($form->get('cvs'));?>
</div>


<div class="form-group">
<?php echo $this->formSubmit($form->get('submit'));?>
</div>

<div class="form-group">
<?php echo $this->form()->closeTag();?>
</div>
?>
        </div>

    </div>
    </div>

</div>            