<div class="jumbotron">
    <img src="http://www.chart-house.com/img/home-slides/01.jpg" style="width: 100%"/>
    Dream careers.
Offered here.
</div>

<div class="row">
    <div class="col-sm-8">
    
        <div class="row">
        
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('The Challenge.') ?></h3>
                    </div>
                    <div class="panel-body">

                        <h3>
                            Choose a career you can't outgrow.
                        </h3>
                    
                        <p>
                            You like talking to people and being part of a team.
                            Make the calls to build a business that evolves to help
                            customers protect what's important to them as a State
                            Farm agent. With the support of a Fortune 500 company,
                            this calling is one of a kind.
                            Take your career to a better state.
                        </p>
                        <h3>
                            Make a smart career choice and keep growing. 
                        </h3>
               
                            <div class="row">
                                <div class="col-md-12">
                                    Being a baapchef
                                    publisher offers fulfilling, rewarding career growth - while working for something
                                    you believe in. It means a career where your life, your work, your values
                                    and your goals are in sync; where you're in the right place at the right time,
                                    doing the right things for the right reasons.
                                </div>
                            </div>
                            <hr/>
                            <div class="row">
                                <div class="col-md-6">
                                    That's what being a baapchef publisher is all about.
                                    It's about building a successful business by helping
                                    people in your community.
                                    On the pages that follow, you'll find general
                                    information about becoming a baapchef publisher.
                                    More than 18,000 State Farm agents serve our
                                    customers across the United States.
                                </div>
                                
                                <div class="col-md-6">
                                    Their backgrounds and experiences are diverse,
                                    but this they share...
                                    They have chosen a career that offers the flexibility to
                                    balance their lives.
                                    All of this, with the support, stability and strength
                                    of the State Farm brand behind them.
                                </div>
                            </div>
                        
                    </div>
                </div>
            </div>
        </div>
    		
        <div class="row">
        
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('Service Plan') ?></h3>
                    </div>
                    <div class="panel-body">
                    	<table style="width: 100%; border: 2px solid green;">
                    	   <thead style="background-color: green; color: white">
                    	   <tr>
                    	       <td style="padding: 10px">&nbsp;</td>
                    	       <td>Agent Silver</td>
                    	       <td>Agent Gold</td>
                    	       <td>Agent Dimond</td>
                    	   </tr>
                    	   </thead>
                    	   <tbody>
                    	   <tr>
                    	       <td style="padding: 10px">Monthly Charge</td>
                    	       <td>Free</td>
                    	       <td>$ 10.49</td>
                    	       <td>$ 20.49</td>
                    	   </tr>
                    	   <tr>
                    	       <td style="padding: 10px">Register restaurant and for initial $ 100 service charge</td>
                    	       <td>20%</td>
                    	       <td>30%</td>
                    	       <td>50%</td>
                    	   </tr>                    	   
                    	   <tr>
                    	       <td style="padding: 10px">Takeout Commission ( $ 0.10 per dish )</td>
                    	       <td></td>
                    	       <td><span class="glyphicon glyphicon-ok"></span></td>
                    	       <td><span class="glyphicon glyphicon-ok"></span></td>
                    	   </tr>
                    	   </tbody>                    	   
                    	</table>
                    	
                    	Agent Gold is automatically upgrade when agent has more than 20 restaurants.
                    	
                    </div>
                </div>
            </div>
        </div>
         					
    
        <div class="row">
        
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('Seafood with a Perfect View') ?></h3>
                    </div>
                    <div class="panel-body">
                            <p style="text-align: center; width: 100%">
                            <img alt="" src="/img/statistics.png" style="width:60%">
                            </p>
                            <p>
                                <b>Chart House - Seafood with a Perfect View</b>
                            </p>
                            <p>
                                For more than 50 years, Chart House has redefined the ideal dining experience. 
                                With 28 waterfront and showcase locations ranging from the historic to the unforgettable, 
                                Chart House restaurants specialize in dazzling views, unique cuisine and exceptional service. 
                            </p>  
                                    
                    </div>
                </div>
            </div>
        </div>
    	  	
    					
    </div>
    
    <div class="col-sm-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Registration Form') ?></h3>
            </div>
            <div class="panel-body">    
          	     <form role="form" method="post" action="/agent/auth/register">
            		<div class="form-group">
        				<label for="name">Name:</label>
        				<input type="text" class="form-control" id="name" name="name" placeholder="John Doe">
        			</div>
    
        			<div class="form-group">
        				<label for="name">Email:</label>
        				<input type="email" class="form-control" id="email" name="email" placeholder="sample@email.com">
        			</div>
        			
        			<div class="form-group">
        				<label for="name">Phone:</label>
        				<input type="tel" class="form-control" id="phone" name="phone" placeholder="4085551212">
        			</div>    			    			
        			
        			<hr/>
        			
        			<div class="form-group">
        				<label for="name">City:</label>
        				<input type="text" class="form-control" id="city" name="city" placeholder="">
        			</div>
        			
         			<div class="form-group">
        				<label for="name">State:</label>
        				<input type="text" class="form-control" id="state" name="state" placeholder="CA">
        			</div>

         			<div class="form-group">
        				<label for="name">Zip Code:</label>
        				<input type="text" class="form-control" id="zipcode" name="zipcode" placeholder="95134">
        			</div>
        			        			
         			<div class="form-group">
        				<label for="name">Country:</label>
        				<input type="text" class="form-control" id="country" name="country" value="US">
        			</div>
        			    			
        			<button type="submit" class="btn btn-default">Submit</button>
        		</form>
        </div>
        </div>
    </div>        
</div>
