<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Reservation\Module'                        => __DIR__ . '/Module.php',
    'Reservation\Controller\ReservationController' => __DIR__ . '/src/Reservation/Controller/ReservationController.php',
    'ReservationTest\Framework\TestCase'        => __DIR__ . '/tests/Reservation/Framework/TestCase.php',
    'ReservationTest\SampleTest'                => __DIR__ . '/tests/Reservation/SampleTest.php',
);
