<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'System\Module'                        => __DIR__ . '/Module.php',
    'System\Controller\SystemController' => __DIR__ . '/src/System/Controller/SystemController.php',
    'SystemTest\Framework\TestCase'        => __DIR__ . '/tests/System/Framework/TestCase.php',
    'SystemTest\SampleTest'                => __DIR__ . '/tests/System/SampleTest.php',
);
