<?php

$title = 'Alerts';
$this->headTitle($title);
?>

<div class="row">

     <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left" style="padding-top: 7.5px;"><?php echo $this->translate($title) ?></h3>
                <div class="btn-group pull-right">
                    <a class="btn btn-default btn-sm" href="<?php echo $this->url('adminalert', array('action'=>'add'));?>">Add</a>
                </div>
            </div>
            <div class="panel-body">
            
                 <table class="table">
                 <thead>
                     <tr>
                         <th>Type</th>
                         <th>Create</th>
                         <th>Content</th>
                         <th>&nbsp;</th>
                     </tr>
                </thead>
                <tbody>            
                     <?php foreach ($alerts as $alert) : ?>
                     <tr>
                         <td style="vertical-align: middle;" ><?php echo $this->escapeHtml($alert->level);?></td>
                         <td style="vertical-align: middle;" ><?php echo $this->escapeHtml($alert->createdate);?></td>
                         <td style="vertical-align: middle;" >
                            <b><?php echo $this->escapeHtml($alert->subject);?></b><br/>
                            <?php echo $this->escapeHtml($alert->note);?>
                         </td>
                         <td style="vertical-align: middle;" >
                         </td>
                     </tr>
                     <?php endforeach; ?>
                </tbody>        
                </table>
                
            </div>
        </div>      
    </div>   
</div>