<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Restaurant\Module'                        => __DIR__ . '/Module.php',
    'Restaurant\Controller\RestaurantController' => __DIR__ . '/src/Restaurant/Controller/RestaurantController.php',
    'RestaurantTest\Framework\TestCase'        => __DIR__ . '/tests/Restaurant/Framework/TestCase.php',
    'RestaurantTest\SampleTest'                => __DIR__ . '/tests/Restaurant/SampleTest.php',
);
