<?php

$title = 'My dish groups';
$this->headTitle($title);
?>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left" style="padding-top: 7.5px;"><?php echo $this->translate($title) ?></h3>
                <div class="btn-group pull-right">
                    <a class="btn btn-default btn-sm" href="<?php echo $this->url('restdishgroup', array('action'=>'add'));?>">Add</a>
                </div>
            </div>
            <div class="panel-body">

                 <table class="table">
                 <thead>
                 <tr>
                     <th>Name</th>
                     <th>Description</th>
                     <th>&nbsp;</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php foreach ($dishgroups as $dishgroup) : ?>
                 <tr>
                     <td data-title="Name"><?php echo $this->escapeHtml($dishgroup->name);?></td>
                     <td data-title="Note"><?php echo $this->escapeHtml($dishgroup->note);?></td>
                     <td data-title="">
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('restdishgroup',
                             array('action'=>'edit', 'id' => $dishgroup->id));?>">Edit</a>
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('restdishgroup',
                             array('action'=>'delete', 'id' => $dishgroup->id));?>">Delete</a>
                     </td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>
            </div>
        </div>
    </div>
</div>  