<?php
$title = 'Add new dish';
$this->headTitle($title);
?>

<link rel="stylesheet" href="/css/dropzone.css?v=1422115121" />

<script type="text/javascript" src="/js/dropzone.js"></script>
<script type="text/javascript" src="/js/jquery.zeroclipboard.min.js"></script>

<script type="text/javascript">

$(document).ready(function(){

	$('#cancelbutton').click(function(){
		parent.history.back();
		return false;
	});

	Dropzone.options.myAwesomeDropzone = {
        maxFiles: 1, // Number of files at a time
        maxFilesize: 10, //in MB
        maxfilesexceeded: function(file)
        {
         alert('You have uploaded more than 1 Image. Only the first file will be uploaded!');
        }, 
    	init: function() {

			this.on("success", function(file, data) { 

				//alert(data.fullname);
				$("#filename").val(data.name);
				$("#imageurl").html(data.url);
				$("#dropzone").hide();
			});
  		}
	}
});



</script>


<div class="row">

<div class="col-sm-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo 'Upload dish image';?></h3>
            </div>
            <div class="panel-body">

                <div id="dropzone">
                	<form action="<?php echo $this->url('admindish', array('action' => 'uploaddragfile')) ?>" class="dropzone" id="my-awesome-dropzone" method="post" enctype="multipart/form-data">
                		<input type="hidden" name="dishfilename" id="dishfilename" value=""/>
                		<div class="dz-message">
                    		Drop files here or click to upload.<br />
                  		</div>
                	</form>
                </div>
                
                <div id='imageurl'></div>            
            
            </div>
        </div>
</div>


    <div class="col-sm-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
            <div class="panel-body">
            
<?php

$form->setAttribute('action', $this->url('admindish', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('rid'));
?>


<div class="form-group">
<?php echo $this->formRow($form->get('name'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('groupid'));?>
</div>

<div class="form-group">
<?php echo $this->formLabel($form->get('price'));?>
<div class="input-group">
<div class="input-group-addon">$</div>
<?php echo $this->formInput($form->get('price'));?>
</div>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('note'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('filename'));?>
</div>

<div class="form-group">
<?php echo $this->formSubmit($form->get('submit'));?>
&nbsp;<?php echo $this->formelement($form->get('cancel'));?>
</div>

<?php
echo $this->form()->closeTag();

?>

            </div>
        </div>
    </div>
</div>