<script type="text/javascript">
<!--
$(document).ready(function(){
	$('#cancelbutton').click(function(){
		parent.history.back();
		return false;
	});
});
-->
</script>

	
<div class="row">
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Table Form</h3>
			</div>
			<div class="panel-body">
			
                <?php
                    $form = $this->form;
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id'));
                    echo $this->formHidden($form->get('rid'));                    
                ?>
                
                    <div class="form-group">					
                            
                        <?php echo $this->formRow($form->get('num')); ?>
                    </div>
                
                    <div class="form-group">					
                            
                        <?php echo $this->formRow($form->get('name')); ?>
                    </div>
                    
                    <div class="form-group">
                        <?php echo $this->formRow($form->get('status'));?>
                    </div>                    
                                                            
                    <div class="form-group">					
                            
                        <?php echo $this->formRow($form->get('note')); ?>
                    </div>
                    
                    <div class="form-group">					
				        <?php
                        echo $this->formElement($form->get('submit'));
                        ?>
                        &nbsp;
                        <?php
                        echo $this->formElement($form->get('cancel'));
                        ?>                            
                    </div>   
                          
                <?php
                echo $this->form()->closeTag($form);
                ?>
                
            </div>
		</div>
	</div>
</div>