<?php
$title = 'Edit Restaurant';
$title2 = 'Add Address';
$this->headTitle($title);
?>

<link rel="stylesheet" href="/css/dropzone.css?v=1422115121" />

<script type="text/javascript" src="/js/dropzone.js"></script>
<script type="text/javascript" src="/js/jquery.zeroclipboard.min.js"></script>
<script src="http://maps.googleapis.com/maps/api/js"></script>

<script type="text/javascript">

$(document).ready(function(){
	$('#cancelbutton').click(function(){
		parent.history.back();
		return false;
	});

	Dropzone.options.myAwesomeDropzone = {
        maxFiles: 1, // Number of files at a time
        maxFilesize: 10, //in MB
        maxfilesexceeded: function(file)
        {
         alert('You have uploaded more than 1 Image. Only the first file will be uploaded!');
        }, 
    	init: function() {

			this.on("success", function(file, data) { 

				$("#imageurl").html(data.url);
				$("#dropzone").hide();
			});
  		}
	}	
});

var myCenter=new google.maps.LatLng(<?php echo $address->lat ?> , <?php echo $address->lng ?>);

function initialize()
{
    var mapProp = {
      center:myCenter,
      zoom:10,
      mapTypeId:google.maps.MapTypeId.ROADMAP
      };

    var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
    
    var myCity = new google.maps.Circle({
    	  center:myCenter,
    	  radius:1600,
    	  strokeColor:"#0000FF",
    	  strokeOpacity:0.8,
    	  strokeWeight:2,
    	  fillColor:"#0000FF",
    	  fillOpacity:0.4
    	  });

	myCity.setMap(map);

}

google.maps.event.addDomListener(window, 'load', initialize);

</script>

<div class="row">

    <div class="col-sm-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo 'Upload restaurant image';?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <img src="<?php echo $this->escapeHtml($restaurant->image)?>" />
                </p>
                
                <div id="dropzone">
                	<form action="<?php echo $this->url('adminrestaurant', array('action' => 'uploaddragfile')) ?>" class="dropzone" id="my-awesome-dropzone" method="post" enctype="multipart/form-data">
                		<input type="hidden" name="dishfilename" id="dishfilename" value=""/>
                		<div class="dz-message">
                    		Drop files here or click to upload.<br />
                  		</div>
                	</form>
                </div>
                
                <div id='imageurl'></div>            
            
            </div>
        </div>
    </div>

    <div class="col-sm-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
            <div class="panel-body">

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'restaurant',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

<div class="form-group">
<?php echo $this->formRow($form->get('name'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('email'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('phone'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('level'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('status'));?>
</div>

<hr/>

<div class="form-group">
<?php echo $this->formLabel($form->get('tax'));?>
<div class="input-group">
<?php echo $this->formInput($form->get('tax'));?>
<div class="input-group-addon">%</div>
</div>
</div>

<div class="form-group">
<?php echo $this->formSubmit($form->get('submit'));?>
&nbsp;<?php echo $this->formelement($form->get('cancel'));?>
</div>

<?php
echo $this->form()->closeTag();

?>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-8">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo 'Restaurant location';?></h3>
            </div>
            <div class="panel-body">

            <div id="googleMap" style="width:100%;height:300px;"></div>
            
            </div>
        </div>
    </div>
</div>
    
<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left" style="padding-top: 7.5px;"><?php echo $this->translate($title2) ?></h3>
                <div class="btn-group pull-right">
                    <a class="btn btn-default btn-sm" href="<?php echo $this->url('adminrestaddress', array('action'=>'add'));?>">Add</a>
                </div>
            </div>
            <div class="panel-body">

                 <table class="table">
                 <thead>
                 <tr>
                     <th>Address1</th>
                     <th>Address2</th>
                     <th>City</th>
                     <th>State</th>
                     <th>Zip</th>
                     <th>Country</th>
                     <th>&nbsp;</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php foreach ($addresses as $address) : ?>
                 <tr>
                     <td><?php echo $this->escapeHtml($address->address1);?></td>
                     <td><?php echo $this->escapeHtml($address->address2);?></td>
                     <td><?php echo $this->escapeHtml($address->city);?></td>
                     <td><?php echo $this->escapeHtml($address->state);?></td>
                     <td><?php echo $this->escapeHtml($address->zip);?></td>
                     <td><?php echo $this->escapeHtml($address->country);?></td>
                     <td>
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('adminrestaddress',
                             array('action'=>'edit', 'id' => $address->id));?>">Edit</a>
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('adminrestaddress',
                             array('action'=>'delete', 'id' => $address->id));?>">Delete</a>
                     </td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>
                 
            </div>
        </div>
    </div>
</div>