<?php
$title = 'Add new user';
$this->headTitle($title);
?>

<style>
<!--
form label, form label span {
 display: block;
}
-->
</style>

<div class="row">
<div class="col-sm-4" style="background-color:#6495ED">

<h2><?php echo $this->escapeHtml($title); ?></h2>
<?php

$form->setAttribute('action', $this->url('adminuser', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('usertype'));
echo $this->formHidden($form->get('rid'));
?>

<div class="form-group">
<?php echo $this->formRow($form->get('name'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('email'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('phone'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('password'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('role_id'));?>
</div>

<div class="form-group">
<?php echo $this->formSubmit($form->get('submit'));?>
</div>

<?php 
echo $this->form()->closeTag();

?>

</div>
</div>