<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Dish\Module'                        => __DIR__ . '/Module.php',
    'Dish\Controller\DishController' => __DIR__ . '/src/Dish/Controller/DishController.php',
    'DishTest\Framework\TestCase'        => __DIR__ . '/tests/Dish/Framework/TestCase.php',
    'DishTest\SampleTest'                => __DIR__ . '/tests/Dish/SampleTest.php',
);
