<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AlbumRest\Module'                        => __DIR__ . '/Module.php',
    'AlbumRest\Controller\AlbumRestController' => __DIR__ . '/src/AlbumRest/Controller/AlbumRestController.php',
    'AlbumRestTest\Framework\TestCase'        => __DIR__ . '/tests/AlbumRest/Framework/TestCase.php',
    'AlbumRestTest\SampleTest'                => __DIR__ . '/tests/AlbumRest/SampleTest.php',
);
