<?php

$title = 'Cart Items';
$this->headTitle($title);
?>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left" style="padding-top: 7.5px;"><?php echo $this->translate($title) ?></h3>
                <div class="btn-group pull-right">
                    <a class="btn btn-default btn-sm" href="<?php echo $this->url('myorder',array('action' => 'ordernow', 'id' => $id));?>">Order Now</a>
                </div>
            </div>
            <div class="panel-body">
            
                 <table class="table">
                 <thead>
                 <tr>
                     <th>Dish</th>
                     <th>Name</th>
                     <th>Quantity</th>
                     <th>Note</th>
                     <th>&nbsp;</th>
                 </tr>
                 </thead>
                 <tbody>                 
                 <?php foreach ($cartitems as $cartitem) : ?>
                 <tr>
                     <td>
                        <img src="<?php echo $this->escapeHtml($cartitem->image)?>" style="width: 200px"/>
                     </td>
                     <td style="vertical-align: middle;" data-title="Name"><?php echo $this->escapeHtml($cartitem->name);?></td>
                     <td style="vertical-align: middle;" data-title="Quantity"><?php echo $this->escapeHtml($cartitem->qty);?></td>
                     <td style="vertical-align: middle;" data-title="Note"><?php echo $this->escapeHtml($cartitem->note);?></td>
                     <td style="vertical-align: middle;">
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('cartitem',
                             array('action'=>'edit', 'id' => $cartitem->id));?>">Edit</a>
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('cartitem',
                             array('action'=>'delete', 'id' => $cartitem->id));?>">Delete</a>
                     </td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>

            </div>
        </div>
    </div>
</div>      