<?php
$title = 'Orders';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>


<table class="table">
 <tr>
     <th>Order ID</th>
     <th>Restaurant</th>
     <th>Order Date</th>
     <th>Schedule Date</th>
     <th>Take Out</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($orders as $order) : ?>
 <tr>
    <td><?php echo $this->escapeHtml($order->id);?></td>
    <td style="width: 200px">
        <img src="<?php echo $this->escapeHtml($order->rimage)?>"  style="width: 200px" />
    </td>     
     <td><?php echo $this->escapeHtml($order->orderdate);?></td>
     <td><?php echo $this->escapeHtml($order->scheduledate);?></td>
     <td><?php echo $this->escapeHtml($order->takeoutdate);?></td>
     <td>
         <a href="<?php echo $this->url('myorderitem',
             array('action'=>'index', 'id' => $order->id));?>">View</a>
     </td>
 </tr>
 <?php endforeach; ?>
  </table>