<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cart\Module'                        => __DIR__ . '/Module.php',
    'Cart\Controller\CartController' => __DIR__ . '/src/Cart/Controller/CartController.php',
    'CartTest\Framework\TestCase'        => __DIR__ . '/tests/Cart/Framework/TestCase.php',
    'CartTest\SampleTest'                => __DIR__ . '/tests/Cart/SampleTest.php',
);
