<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Waiting\Module'                        => __DIR__ . '/Module.php',
    'Waiting\Controller\WaitingController' => __DIR__ . '/src/Waiting/Controller/WaitingController.php',
    'WaitingTest\Framework\TestCase'        => __DIR__ . '/tests/Waiting/Framework/TestCase.php',
    'WaitingTest\SampleTest'                => __DIR__ . '/tests/Waiting/SampleTest.php',
);
