<?php
$title = 'PinIn';
$this->headTitle($title);
?>

<script type="text/javascript">
<!--
$(document).ready(function(){
	$('#cancelbutton').click(function(){
		parent.history.back();
		return false;
	});
});
-->
</script>

<div class="row">

    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Change Your password') ?></h3>
            </div>
            <div class="panel-body">

                <div class="row">

                    <div class="col-md-4">            
                        <p>
                        Please complete the following form to change your password.
                        </p>
                        
                  	     <form role="form" method="post" action="/customer/auth/changepwd">
                    		    			<div class="form-group">
                				<label for="name">User Name:</label>
                				<input type="email" class="form-control" id="email" name="email" placeholder="example@email.com">
                			</div>
                			
                			<div class="form-group">
                				<label for="name">Expired Password:</label>
                				<input type="password" class="form-control" id="oldpwd" name="oldpwd" placeholder="********">
                			</div>    			    			
        
                			<div class="form-group">
                				<label for="name">New Password:</label>
                				<input type="password" class="form-control" id="newpwd" name="newpwd" placeholder="********">
                			</div>   
        
                			<div class="form-group">
                				<label for="name">Verify New Password:</label>
                				<input type="password" class="form-control" id="confirmpwd" name="confirmpwd" placeholder="********">
                			</div>           			
                			
                			<button type="submit" class="btn btn-primary">Save</button>
                			<button type="submit" class="btn btn-default" id="cancelbutton">Cancel</button>
                		</form>
                    </div>
                    
                    
                    <div class="col-md-8">            
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"><?php echo $this->translate('Helpful Tips') ?></h3>
                            </div>
                            <div class="panel-body">
                                <p>
                                For your security, new passwords must meet the following requirements:
                                </p>
                                <ul>
                                    <li>must be between 8 to 40 characters in length</li>
                                    <li>must contain at least one upper case character, on lower case character and one number</li>
                                    <li>cannot be a previous used password</li>
                                    <li>avoid using special characters</li>
                                </ul>
                                
                                For enhanced security, do not use proper names, words commonly found 
                                in the dictionary or repeating sequences of numbers.
                                
                            </div>
                        </div>
                    </div>                    
                    
                </div>
                
                                   
             </div>
        </div>
    </div>

</div>