<?php

$title = 'Orders';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('order', array('action'=>'add'));?>">Add new Order</a>
 </p>

 <table class="table">
 <tr>
     <th>Order ID</th>
     <th>Restaurant</th>
     <th>Customer</th>
     <th>Order Date</th>
     <th>Schedule Date</th>
     <th>Take Out</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($orders as $order) : ?>
 <tr>
 <td><?php echo $this->escapeHtml($order->id);?></td>
     <td><?php echo $this->escapeHtml($order->rid);?></td>
     <td><?php echo $this->escapeHtml($order->cid);?></td>
     <td><?php echo $this->escapeHtml($order->orderdate);?></td>
     <td><?php echo $this->escapeHtml($order->scheduledate);?></td>
     <td><?php echo $this->escapeHtml($order->takeoutdate);?></td>
     <td>
         <a href="<?php echo $this->url('order',
             array('action'=>'edit', 'id' => $order->id));?>">Edit</a>
         <a href="<?php echo $this->url('order',
             array('action'=>'delete', 'id' => $order->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
  </table>