<div class="jumbotron">
    <img src="http://www.chart-house.com/img/home-slides/02.jpg" style="width: 100%"/>
</div>

<div class="row">
    <div class="col-sm-8">

        <div class="row">
            <div class="col-sm-12">
                 <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('Takeout? Easy Step 1-2-3') ?></h3>
                    </div>
                    <div class="panel-body"> 
                        <ol>
                            <li>Customer/Member management system</li>
                            <li>In-Restaurant ordering system</li>
                            <li>Order Notification</li>
                        </ol>                    
                    </div>
                </div>            
            </div>

            <div class="col-sm-12">
                 <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('Invest') ?></h3>
                    </div>
                    <div class="panel-body">
                        It is start up and you can join us. 
                    </div>
                </div>            
            </div>
            
                        
            <div class="col-sm-12">
                 <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('AND More ...') ?></h3>
                    </div>
                    <div class="panel-body"> 
                        <ul>
                            <li>Customer/Member management system</li>
                            <li>In-Restaurant ordering system</li>
                            <li>Order Notification</li>
                        </ul>
                    </div>
                </div>            
            </div>
        </div>        					
    </div>
    
    <div class="col-sm-4">
         <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Registration Form') ?></h3>
            </div>
            <div class="panel-body">     
            	<form role="form" method="post" action="/restaurant/auth/register">
            		<div class="form-group">
        				<label for="name">Restaurant Name:</label>
        				<input type="text" class="form-control" id="name" name="name" placeholder="Enter restaurant name">
        			</div>
    
        			<div class="form-group">
        				<label for="name">Email:</label>
        				<input type="email" class="form-control" id="email" name="email" placeholder="example@email.com">
        			</div>
        			
        			<div class="form-group">
        				<label for="name">Phone:</label>
        				<input type="tel" class="form-control" id="phone" name="phone" placeholder="4085551212">
        			</div>    			    			
        			
        			<hr/>
        			
        			<div class="form-group">
        				<label for="name">Address1:</label>
        				<input type="text" class="form-control" id="address1" name="address1" placeholder="Enter address">
        			</div>
        			
        			<div class="form-group">
        				<label for="name">Address2:</label>
        				<input type="text" class="form-control" id="address2" name="address2" placeholder="Enter address">
        			</div>
        			
        			<div class="form-group">
        				<label for="name">City:</label>
        				<input type="text" class="form-control" id="city" name="city" placeholder="Enter city">
        			</div>
        			
         			<div class="form-group">
        				<label for="name">State:</label>
        				<input type="text" class="form-control" id="state" name="state" placeholder="CA">
        			</div>

         			<div class="form-group">
        				<label for="name">Zip Code:</label>
        				<input type="text" class="form-control" id="zipcode" name="zipcode" placeholder="95134">
        			</div>        			
        			
         			<div class="form-group">
        				<label for="name">Country:</label>
        				<input type="text" class="form-control" id="country" name="country" value="US">
        			</div>
        			
         			<hr/>       			
        			    	
         			<div class="form-group">
        				<label for="name">Tax:</label>
        				<div class="input-group">
            				<input type="text" class="form-control" id="tax" name="tax" placeholder="9.75">
            				<div class="input-group-addon">%</div>
            			</div>	
        			</div>
        			        			    			
        			<button type="submit" class="btn btn-default">Submit</button>
        		</form>
    	   </div>
        </div>
    </div>
</div>
