<div class="row">
	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Request Form</h3>
			</div>
			<div class="panel-body">
			
                <?php
                    $form = $this->form;
                    $form->prepare();
                    echo $this->form()->openTag($form);
                ?>
                
                    <div class="form-group">					
                            
                        <?php echo $this->formRow($form->get('email')); ?>
                    </div>
                
                    <div class="form-group">					
                            
                        <?php echo $this->formRow($form->get('subject')); ?>
                    </div>
                
                    <div class="form-group">					
                            
                        <?php echo $this->formRow($form->get('note')); ?>
                    </div>
                    
                    <div class="form-group">					
                        <?php echo $this->formRow($this->form->get('captcha')); ?>
                    </div>
                    
                    <div class="form-group">					
				        <?php
                        echo $this->formRow($form->get('reqCsrf'));
                        echo $this->formElement($form->get('submit'));
                        ?>
                        &nbsp;
                        <?php
                        echo $this->formElement($form->get('cancel'));
                        ?>                            
                    </div>   
                          
                <?php
                echo $this->form()->closeTag($form);
                ?>
                
            </div>
		</div>
	</div>
</div>
