<?php
$title = 'Edit Order';
$this->headTitle($title);
?>

<div class="row">
    <div class="col-sm-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
            <div class="panel-body">

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'order',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

<div class="form-group">
<?php echo $this->formRow($form->get('rid'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('cid'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('dishid'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('scheduledate'));?>
</div>

<div class="form-group">
<?php echo $this->formSubmit($form->get('submit'));?>
&nbsp;<?php echo $this->formelement($form->get('cancel'));?>
</div>

<?php
echo $this->form()->closeTag();
?>

            </div>
        </div>
    </div>
</div>
