<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Alert\Module'                        => __DIR__ . '/Module.php',
    'Alert\Controller\AlertController' => __DIR__ . '/src/Alert/Controller/AlertController.php',
    'AlertTest\Framework\TestCase'        => __DIR__ . '/tests/Alert/Framework/TestCase.php',
    'AlertTest\SampleTest'                => __DIR__ . '/tests/Alert/SampleTest.php',
);
