<?php

$title = 'Restaurants';
$this->headTitle($title);
?>
	
<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left" style="padding-top: 7.5px;"><?php echo $this->translate($title) ?></h3>
                <div class="btn-group pull-right">
                    <a class="btn btn-default btn-sm" href="<?php echo $this->url('adminrestaurant', array('action'=>'add'));?>">Add</a>
                </div>
            </div>
            <div class="panel-body">
                 <table class="table">
                 <thead>
                 <tr>
                    <th>&nbsp;</th>
                     <th>Name</th>
                     <th>Create</th>
                     <th>Email</th>
                     <th>Phone</th>
                     <th>Level</th>
                     <th>Status</th>
                     <th>&nbsp;</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php foreach ($restaurants as $restaurant) : ?>
                 <tr>
                     <td data-title="">
                        <img src="<?php echo $this->escapeHtml($restaurant->image)?>" width=200 />
                     </td>
                     <td style="vertical-align: middle;" data-title="Name">
                        <?php echo $this->escapeHtml($restaurant->name);?>
                     </td>
                     <td style="vertical-align: middle;" data-title="Create"><?php echo $this->escapeHtml($restaurant->createdate);?></td>
                     <td style="vertical-align: middle;" data-title="Email"><?php echo $this->escapeHtml($restaurant->email);?></td>
                     <td style="vertical-align: middle;" data-title="Phone"><?php echo $this->escapeHtml($restaurant->phone);?></td>
                     <td style="vertical-align: middle;" data-title="Level"><?php echo $restaurant->level?></td>
                     <td style="vertical-align: middle;" data-title="Status"><?php echo $restaurant->status?></td>
                     <td style="vertical-align: middle;" data-title="">
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('adminrestaurant',
                             array('action'=>'edit', 'id' => $restaurant->id));?>">Edit</a>
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('adminrestaurant',
                             array('action'=>'delete', 'id' => $restaurant->id));?>">Delete</a>
                     </td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>
            </div>
        </div>
    </div>
</div>                        