<h3>Reset Password</h3>

<div>
    <table>
        <tr style="width: 100px">
            <td>Name</td>
            <td><?php echo $user->name;?></td>
        </tr>
        <tr>
            <td>Id</td>
            <td><?php echo $user->email;?></td>
        </tr>
        <tr>
            <td>Password</td>
            <td><?php echo $this->password;?></td>
        </tr>                
    </table>
</div>