<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Reward\Module'                        => __DIR__ . '/Module.php',
    'Reward\Controller\RewardController' => __DIR__ . '/src/Reward/Controller/RewardController.php',
    'RewardTest\Framework\TestCase'        => __DIR__ . '/tests/Reward/Framework/TestCase.php',
    'RewardTest\SampleTest'                => __DIR__ . '/tests/Reward/SampleTest.php',
);
