<script type="text/javascript">

$(document).ready(function(){
	$('#cancelbutton').click(function(){
		parent.history.back();
		return false;
	});

	$("#remember").bootstrapSwitch();
});



</script>

<?php
$flashMessage = $this->flashMessenger()->getMessages();

if (count($flashMessage)) :
    ?>
<div class="row">
	<ul>
        <?php
    foreach ($flashMessage as $msg) :
        foreach ($msg as $type => $message) :
            ?>
            <li><span class="<?php echo $type; ?>"><?php echo $message; ?></span></li>
        <?php endforeach; ?>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <?php if(isset($this->messages)) : ?>
    <ul>
        <?php foreach ($this->messages as $type => $msg) : ?>
        <li><span class="<?php echo $type; ?>"><?php echo $msg; ?></span></li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
<div class="row">
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Login</h3>
			</div>
			<div class="panel-body">
			    <?php
                $form = $this->loginForm;
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                
                <div class="form-group">
                <?php echo $this->formRow($form->get('email')); ?>
                </div>
                
                <div class="form-group">
                <?php echo $this->formRow($form->get('password')); ?>
                </div>
                
                <div class="form-group">
                <?php echo $this->formLabel($form->get('remember')); ?>
                <br/>
                <?php echo $this->formInput($form->get('remember')); ?>
                </div>
                                
                <div class="form-group">
                <?php
                echo $this->formRow($form->get('loginCsrf'));
                echo $this->formElement($form->get('submit'));
                ?>
                &nbsp;
                <?php
                echo $this->formElement($form->get('cancel'));
                ?>                
                </div>
                
                <?php
                echo $this->form()->closeTag($form);
                ?>
            </div>
		</div>

		<div class="panel-footer">
		    DEMO
		    <br/>
            email : demo@customer.com
            <br/>
            password : 12345678
		
		</div>		
	</div>
</div>