<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Charge\Module'                        => __DIR__ . '/Module.php',
    'Charge\Controller\ChargeController' => __DIR__ . '/src/Charge/Controller/ChargeController.php',
    'ChargeTest\Framework\TestCase'        => __DIR__ . '/tests/Charge/Framework/TestCase.php',
    'ChargeTest\SampleTest'                => __DIR__ . '/tests/Charge/SampleTest.php',
);
