<?php
$title = 'Add new dish';
$this->headTitle($title);
?>

<div class="row">
<div class="col-sm-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
        <div class="panel-body">
        
<?php

$form->setAttribute('action', $this->url('restdish', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>


<div class="form-group">
<?php echo $this->formRow($form->get('name'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('groupid'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('price'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('note'));?>
</div>

<div class="form-group">
<?php echo $this->formSubmit($form->get('submit'));?>
</div>

<?php
echo $this->form()->closeTag();

?>
        </div>
    </div>        
    </div>
</div>
