<?php

$title = 'Takeout Dishes';
$this->headTitle($title);
?>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left" style="padding-top: 7.5px;"><?php echo $this->translate($title) ?></h3>
                <div class="btn-group pull-right">
                    <a class="btn btn-default btn-sm" href="<?php echo $this->url('restdish', array('action'=>'add'));?>">Add</a>
                </div>
            </div>
            <div class="panel-body">
            
                 <table class="table">
                 <thead>
                 <tr>
                     <th>Dish</th>
                     <th>Name</th>
                     <th>Price</th>
                     <th>Description</th>
                     <th>&nbsp;</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php foreach ($dishes as $dish) : ?>
                 <tr>
                     <td>
                        <img src="<?php echo $this->escapeHtml($dish->image)?>" style="width:200px"/>
                     </td>
                     <td  style="vertical-align: middle;" data-title="Dish"><?php echo $this->escapeHtml($dish->name);?></td>
                     <td style="vertical-align: middle;" data-title="Price">$ <?php echo $this->escapeHtml($dish->price);?></td>
                     <td style="vertical-align: middle;" data-title="Note"><?php echo $this->escapeHtml($dish->note);?></td>
                     <td style="vertical-align: middle;" data-title="">
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('restdish',
                             array('action'=>'edit', 'id' => $dish->id));?>">Edit</a>
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('restdish',
                             array('action'=>'delete', 'id' => $dish->id));?>">Delete</a>
                     </td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>
                 
            </div>
        </div>
    </div>
</div>      