<?php

$title = 'Customers';
$this->headTitle($title);
?>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left" style="padding-top: 7.5px;"><?php if($current_restaurant){ echo $current_restaurant->name;} ?></h3>
                <div class="btn-group pull-right">
                      <div class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" >Restaurant &nbsp;&nbsp;<span class="caret" ></span></button>
                        <ul class="dropdown-menu">
                          <?php foreach ($restaurants as $restaurant) : ?>
                            <li><a href="<?php echo $this->url('admincustomer', array('action'=>'index', 'id' => $restaurant->id));?>"><?php echo $this->escapeHtml($restaurant->name);?></a></li>
                          <?php endforeach; ?>
                        </ul>
                      </div>
                </div>
            </div>
        </div>            
    </div>

    <?php if($current_restaurant){  ?>
    
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left" style="padding-top: 7.5px;"><?php echo $this->translate($title) ?></h3>
                <div class="btn-group pull-right">
                    <a class="btn btn-default btn-sm" href="<?php echo $this->url('admincustomer', array('action'=>'add'));?>">Add</a>
                </div>
            </div>
            <div class="panel-body">
            
                 <table class="table">
                 <thead>
                 <tr>
                     <th>&nbsp;</th>
                     <th>Name</th>
                     <th>Email</th>
                     <th>Phone</th>
                     <th>&nbsp;</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php foreach ($customers as $customer) : ?>
                 <tr>
                     <td>
                        <img src="<?php echo $this->escapeHtml($customer->image)?>" style="width:64px"/>
                     </td>
                     <td  style="vertical-align: middle;" data-title="Name">
                        <?php echo $this->escapeHtml($customer->name);?>
                     </td>
                     <td style="vertical-align: middle;" data-title="Email"><?php echo $this->escapeHtml($customer->email);?></td>
                     <td style="vertical-align: middle;" data-title="Phone"><?php echo $this->escapeHtml($customer->phone);?></td>
                     <td style="vertical-align: middle;" data-title="">
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('admincustomer',
                             array('action'=>'edit', 'id' => $customer->id));?>">Edit</a>
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('admincustomer',
                             array('action'=>'delete', 'id' => $customer->id));?>">Delete</a>
                     </td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>

            </div>
        </div>
    </div>
    <?php }  ?>
</div>      