<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Creditcard\Module'                        => __DIR__ . '/Module.php',
    'Creditcard\Controller\CreditcardController' => __DIR__ . '/src/Creditcard/Controller/CreditcardController.php',
    'CreditcardTest\Framework\TestCase'        => __DIR__ . '/tests/Creditcard/Framework/TestCase.php',
    'CreditcardTest\SampleTest'                => __DIR__ . '/tests/Creditcard/SampleTest.php',
);
