<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Account') ?></h3>
            </div>
            <div class="panel-body">
            <ul class="list-group">
              <li class="list-group-item"><a href="<?php echo $this->url('agent',
                             array('action'=>'edit'));?>"><span class="glyphicon glyphicon-edit"></span> Edit Profile</a></li>
              <li class="list-group-item"><a href="<?php echo $this->url('agentauth',
                             array('action'=>'changepwd'));?>"><span class="glyphicon glyphicon-lock"></span> Change password</a></li>
              <li class="list-group-item"><a href="<?php echo $this->url('myprofile',
                             array('action'=>'pushnotification'));?>"><span class="glyphicon glyphicon-bullhorn"></span> Push Notifications</a></li>
            </ul>
             </div>
        </div>
    </div>
</div>
    
<div class="row">
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('About') ?></h3>
            </div>
            <div class="panel-body">
                <ul class="list-group">
                  <li class="list-group-item"><span class="glyphicon glyphicon-edit"></span> Baapchef Guide</li>
                  <li class="list-group-item"><span class="glyphicon glyphicon-edit"></span> About Baapchef</li>
                  <li class="list-group-item"><span class="glyphicon glyphicon-edit"></span> Term of use</li>
                  <li class="list-group-item"><span class="glyphicon glyphicon-edit"></span> Private policy</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Update') ?></h3>
            </div>
            <div class="panel-body">
                <ul class="list-group">
                  <li class="list-group-item">
                    <span class="badge">1.2</span> App Version
                  </li>
                </ul>         
            </div>
        </div>
    </div>

</div>