<?php

$title = 'Order Items';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('orderitem', array('action'=>'add'));?>">Add new OrderItem</a>
 </p>

 <table class="table">
 <tr>
     <th>Order Item ID</th>
     <th>Cart ID</th>
     <th>Dish ID</th>
     <th>Quantity</th>
     <th>Note</th>
     <th>Create Date</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($orderitems as $orderitem) : ?>
 <tr>
 <td><?php echo $this->escapeHtml($orderitem->id);?></td>
     <td><?php echo $this->escapeHtml($orderitem->cartid);?></td>
     <td><?php echo $this->escapeHtml($orderitem->dishid);?></td>
     <td><?php echo $this->escapeHtml($orderitem->qty);?></td>
     <td><?php echo $this->escapeHtml($orderitem->note);?></td>
     <td><?php echo $this->escapeHtml($orderitem->createdate);?></td>
     <td>
         <a href="<?php echo $this->url('orderitem',
             array('action'=>'edit', 'id' => $orderitem->id));?>">Edit</a>
         <a href="<?php echo $this->url('cartitem',
             array('action'=>'delete', 'id' => $orderitem->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
  </table>