<?php
$title = 'Restaurant';
$this->headTitle($title);
?>

<script src="http://maps.googleapis.com/maps/api/js"></script>
<script>

var myCenter=new google.maps.LatLng(<?php echo $address->lat ?> , <?php echo $address->lng ?>);

function initialize()
{
    var mapProp = {
      center:myCenter,
      zoom:10,
      mapTypeId:google.maps.MapTypeId.ROADMAP
      };

    var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
    
    var myCity = new google.maps.Circle({
    	  center:myCenter,
    	  radius:1600,
    	  strokeColor:"#0000FF",
    	  strokeOpacity:0.8,
    	  strokeWeight:2,
    	  fillColor:"#0000FF",
    	  fillOpacity:0.4
    	  });

	myCity.setMap(map);

}

google.maps.event.addDomListener(window, 'load', initialize);
</script>


<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate($title) ?></h3>
            </div>
            <div class="panel-body">

                     <div>
                        <img src="<?php echo $this->escapeHtml($restaurant->image)?>" width=200 />
                     </div>
                     <div style="vertical-align: middle;" data-title="Name"><?php echo $this->escapeHtml($restaurant->name);?></div>
                     <div style="vertical-align: middle;" data-title="Phone"><?php echo $this->escapeHtml($restaurant->phone);?></div>
            </div>
        </div>
    </div>
</div>         
<div id="googleMap" style="width:500px;height:380px;"></div>
