<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Table\Module'                        => __DIR__ . '/Module.php',
    'Table\Controller\TableController' => __DIR__ . '/src/Table/Controller/TableController.php',
    'TableTest\Framework\TestCase'        => __DIR__ . '/tests/Table/Framework/TestCase.php',
    'TableTest\SampleTest'                => __DIR__ . '/tests/Table/SampleTest.php',
);
