<?php
$title = 'Add new Restaurant';
$this->headTitle($title);
?>

<script type="text/javascript">

$(document).ready(function(){
	$('#cancelbutton').click(function(){
		parent.history.back();
		return false;
	});
});



</script>

<div class="row">
    <div class="col-sm-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
            <div class="panel-body">
            
<?php

$form->setAttribute('action', $this->url('agrestaurant', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('level'));
echo $this->formHidden($form->get('status'));
?>


<div class="form-group">
<?php echo $this->formRow($form->get('name'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('email'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('phone'));?>
</div>

<div class="form-group">
    <?php echo $this->formLabel($form->get('tax'));?>
    <div class="input-group">
    <?php echo $this->formInput($form->get('tax'));?>
    <div class="input-group-addon">%</div>
    </div>
</div>

<div class="form-group">
<?php echo $this->formSubmit($form->get('submit'));?>
&nbsp;<?php echo $this->formElement($form->get('cancel'));?>
</div>

<?php
echo $this->form()->closeTag();

?>
            </div>
        </div>
    </div>
</div>
