<?php
$title = 'Edit Restaurant';
$title2 = 'Add Address';
$this->headTitle($title);
?>

<script type="text/javascript">

$(document).ready(function(){
	$('#cancelbutton').click(function(){
		parent.history.back();
		return false;
	});
});



</script>

<div class="row">
    <div class="col-sm-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
            <div class="panel-body">

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'adminrestaurant',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
?>

<div class="form-group">
<?php echo $this->formRow($form->get('name'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('email'));?>
</div>

<div class="form-group">
<?php echo $this->formRow($form->get('phone'));?>
</div>

<div class="form-group">
    <?php echo $this->formLabel($form->get('tax'));?>
    <div class="input-group">
    <?php echo $this->formInput($form->get('tax'));?>
    <div class="input-group-addon">%</div>
    </div>
</div>

<div class="form-group">
<?php echo $this->formSubmit($form->get('submit'));?>
&nbsp;<?php echo $this->formElement($form->get('cancel'));?>
</div>

<?php
echo $this->form()->closeTag();

?>
            </div>
        </div>
    </div>
</div>


<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left" style="padding-top: 7.5px;"><?php echo $this->translate($title2) ?></h3>
                <div class="btn-group pull-right">
                    <a class="btn btn-default btn-sm" href="<?php echo $this->url('agrestaddress', array('action'=>'add'));?>">Add</a>
                </div>
            </div>
            <div class="panel-body">

                 <table class="table">
                 <thead>
                 <tr>
                     <th>Address1</th>
                     <th>Address2</th>
                     <th>City</th>
                     <th>State</th>
                     <th>Zip</th>
                     <th>Country</th>
                     <th>&nbsp;</th>
                 </tr>
                 </thead>
                 <tbody>
                 <?php foreach ($addresses as $address) : ?>
                 <tr>
                     <td><?php echo $this->escapeHtml($address->address1);?></td>
                     <td><?php echo $this->escapeHtml($address->address2);?></td>
                     <td><?php echo $this->escapeHtml($address->city);?></td>
                     <td><?php echo $this->escapeHtml($address->state);?></td>
                     <td><?php echo $this->escapeHtml($address->zip);?></td>
                     <td><?php echo $this->escapeHtml($address->country);?></td>
                     <td>
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('agrestaddress',
                             array('action'=>'edit', 'id' => $address->id));?>">Edit</a>
                         <a class="btn btn-default btn-sm" href="<?php echo $this->url('agrestaddress',
                             array('action'=>'delete', 'id' => $address->id));?>">Delete</a>
                     </td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
                 </table>
                 
            </div>
        </div>
    </div>
</div>