<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'GoogleMapsTools\Module'                        => __DIR__ . '/Module.php',
    'GoogleMapsTools\Controller\GoogleMapsToolsController' => __DIR__ . '/src/GoogleMapsTools/Controller/GoogleMapsToolsController.php',
    'GoogleMapsToolsTest\Framework\TestCase'        => __DIR__ . '/tests/GoogleMapsTools/Framework/TestCase.php',
    'GoogleMapsToolsTest\SampleTest'                => __DIR__ . '/tests/GoogleMapsTools/SampleTest.php',
);
