<?php
$flashMessage = $this->flashMessenger()->getMessages();

if (count($flashMessage)) :
    ?>
<div class="row">
	<ul>
        <?php
    foreach ($flashMessage as $msg) :
        foreach ($msg as $type => $message) :
            ?>
            <li><span class="<?php echo $type; ?>"><?php echo $message; ?></span></li>
        <?php endforeach; ?>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <?php if(isset($this->messages)) : ?>
    <ul>
        <?php foreach ($this->messages as $type => $msg) : ?>
        <li><span class="<?php echo $type; ?>"><?php echo $msg; ?></span></li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
<div class="row">
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Signup</h3>
			</div>
			<div class="panel-body">
			
                <?php
                $form = $this->signupForm;
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
             
                    <div class="form-group">					
                            
                        <?php echo $this->formRow($form->get('name')); ?>
                            <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('name'));?></span>
                    </div>
                
                    <div class="form-group">					
                            
                        <?php echo $this->formRow($form->get('email')); ?>
                            <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('email'));?></span>
                    </div>
                
                    <div class="form-group">					
                            
                        <?php echo $this->formRow($form->get('phone')); ?>
                            <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('phone'));?></span>
                    </div>
                
                    <div class="form-group">					
                            
                        <?php echo $this->formRow($form->get('password')); ?>
                            <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('password'));?></span>
                    </div>
                
                    <div class="form-group">					
				        <?php
                        echo $this->formRow($form->get('loginCsrf'));
                        echo $this->formSubmit($form->get('submit'));
                        ?>
                        &nbsp;
                        <?php 
                        echo $this->formElement($form->get('cancel'));
                        ?>
                    </div>   
                          
                <?php
                echo $this->form()->closeTag($form);
                ?>
                
            </div>
		</div>
	</div>
</div>