

<link rel="stylesheet" href="/css/dropzone.css?v=1422115121" />

<script type="text/javascript" src="/js/dropzone.js"></script>
<script type="text/javascript" src="/js/jquery.zeroclipboard.min.js"></script>

<script>
$(document).ready(function() {

	Dropzone.options.myAwesomeDropzone = {
        maxFiles: 1, // Number of files at a time
        maxFilesize: 1, //in MB
        maxfilesexceeded: function(file)
        {
         alert('You have uploaded more than 1 Image. Only the first file will be uploaded!');
        }, 
    	init: function() {

			this.on("success", function(file, data) { 

				$("#imageurl").append("<br/>");
				$("#imageurl").append(data.url);
				$("#dropzone").hide();
			});
  		}
	}
});

</script>


<div id="dropzone">
	<form action="/upload/uploaddragfile" class="dropzone" id="my-awesome-dropzone" method="post" enctype="multipart/form-data">
		<div class="dz-message">
    		Drop files here or click to upload.<br />
  		</div>
	</form>
</div>

<br/>
<br/>

<div id='imageurl'>
</div>

