<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Schedule\Module'                        => __DIR__ . '/Module.php',
    'Schedule\Controller\ScheduleController' => __DIR__ . '/src/Schedule/Controller/ScheduleController.php',
    'ScheduleTest\Framework\TestCase'        => __DIR__ . '/tests/Schedule/Framework/TestCase.php',
    'ScheduleTest\SampleTest'                => __DIR__ . '/tests/Schedule/SampleTest.php',
);
