<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-switch.css')
       ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap-switch.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">        
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/bc-logo.png') ?>" alt="Zend Framework 2"/></a>
            </div>        
            <div class="collapse navbar-collapse" id="navbar-collapse">
                    <?php
                        if($this->login == '1')
                        {
                    ?>

                        <ul class="nav navbar-nav">
                            <li ><a href="<?php echo $this->url('agenthome') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <?php if($this->role == 'admin') { ?>
                            <li ><a href="<?php echo $this->url('agprofile') ?>"><?php echo $this->translate('Profile') ?></a></li>
                            <li ><a href="<?php echo $this->url('aguser') ?>"><?php echo $this->translate('User') ?></a></li>
                            <?php } ?>
                            
                            <?php if($this->role != '') { ?>                            
                            <li ><a href="<?php echo $this->url('agrestaurant') ?>"><?php echo $this->translate('Restaurant') ?></a></li>
                            <li ><a href="<?php echo $this->url('agtakeoutdish') ?>"><?php echo $this->translate('Takeout Dish') ?></a></li>
                            <li ><a href="<?php echo $this->url('agdishgroup') ?>"><?php echo $this->translate('Dish Group') ?></a></li>
                            <li ><a href="<?php echo $this->url('agdish') ?>"><?php echo $this->translate('Dish') ?></a></li>
                            <li ><a href="<?php echo $this->url('agorder') ?>"><?php echo $this->translate('Order') ?></a></li>
                            <?php } ?>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                        
                            <li >
                                <a href="<?php echo $this->url('agentauth', array('action' => 'pinout' )) ?>">
                                <span class="glyphicon glyphicon-log-out"></span> <?php echo $this->translate('Pinout') ?></a>
                            </li>                         
                            <li ><a href="<?php echo $this->url('agentauth', array('action' => 'logout')) ?>">
                            <span class="glyphicon glyphicon-logout"></span> <?php echo $this->translate('Logout') ?></a>
                            </li>
                        </ul>        
                    <?php      
                        }
                        else
                        {
                    ?>
                        <ul class="nav navbar-nav navbar-right">
                            <li ><a href="<?php echo $this->url('agentauth', array('action' => 'signup')) ?>">
                            <span class="glyphicon glyphicon-user"></span> <?php echo $this->translate('Signup') ?></a>
                            </li>                        
                            <li ><a href="<?php echo $this->url('agentauth', array('action' => 'login')) ?>">
                            <span class="glyphicon glyphicon-log-in"></span> <?php echo $this->translate('Login') ?></a>
                            </li>
                        </ul>        
                    <?php 
                        }
                     ?> 
                </ul>                 
            </div>  
            </div>
        </nav>
        

        <div class="container">
        
            <?php echo $this->content; ?>
            <hr>
            <footer>
            
                 <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li ><a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About') ?></a></li>
                        <li ><a href="<?php echo $this->url('contactus') ?>"><?php echo $this->translate('Contact Us') ?></a></li>
                        <li ><a href="<?php echo $this->url('faq') ?>"><?php echo $this->translate('FAQ') ?></a></li>
                        <li ><a href="<?php echo $this->url('job') ?>"><?php echo $this->translate('Job') ?></a></li>
                        <li ><a href="<?php echo $this->url('terms') ?>"><?php echo $this->translate('Terms') ?></a></li>
                        <li ><a href="<?php echo $this->url('policy') ?>"><?php echo $this->translate('Policies') ?></a></li>
                        <li ><a href="/application/index/publisher"><?php echo $this->translate('Publisher') ?></a></li>
                    </ul>
                </div>           
            
                <p>&copy; 2005 - <?php echo date('Y') ?> by BaapChef. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
