<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('About Us') ?></h3>
            </div>
            <div class="panel-body">

                <p>
                    BaapChef is the online and mobile food ordering company 
                    established in California, USA and dedicated to 
                    connecting diners with local takeout restaurants.
                </p>
                
                <p>              
                    BaapChef's mission is to vitalize our local restaurants 
                    and establish a sustainable profitable model by providing 
                    online and mobile food ordering platform for the purpose 
                    of directing diners to the right restaurant nearby.
                </p>
            
                <p>              
                    BaapChef's online and mobile ordering platform designed 
                    with critical emphasis on location, human preference for food, 
                    and immediacy of finding sought-for items, and presents 
                    the takeout food items of special interest to diners from 
                    takeout restaurants partnering with us.
                    
                </p>
                <p style="text-align: center">
                    <img alt="echo system" src="/img/image_ecosys.png" style="width: 60%" />
                </p>
            </div>
        </div>
    </div>
</div>