<div class="row">
    <div class="col-sm-6">
    
        <div class="row">
        
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('About Us') ?></h3>
                    </div>
                    <div class="panel-body">

                        <p>
                            BaapChef is the online and mobile food ordering company 
                            established in California, USA and dedicated to 
                            connecting diners with local takeout restaurants.
                        </p>
                        
                        <p>              
                            BaapChef's mission is to vitalize our local restaurants 
                            and establish a sustainable profitable model by providing 
                            online and mobile food ordering platform for the purpose 
                            of directing diners to the right restaurant nearby.
                        </p>
                    
                        <p>              
                            BaapChef's online and mobile ordering platform designed 
                            with critical emphasis on location, human preference for food, 
                            and immediacy of finding sought-for items, and presents 
                            the takeout food items of special interest to diners from 
                            takeout restaurants partnering with us.
                            
                        </p>
                    
                        <img alt="echo system" src="/img/image_ecosys.png" style="width: 100%" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Any Question!!!') ?></h3>
            </div>
            <div class="panel-body">
    
        		<form role="form" method="post" action="contactus">
    
        		    <div class="form-group">
        				<label for="name">Email:</label>
        				<input type="email" class="form-control" id="email" name="email" placeholder="sample@email.com">
        			</div>
        			
        			<div class="form-group">
        				<label for="name">Phone:</label>
        				<input type="text" class="form-control" id="phone" name="phone" placeholder="4085551212">
        			</div> 
        			   			    			
        			<div class="form-group">
        				<label for="name">Subject:</label>
        				<input type="text" class="form-control" id="subject" name="subject">
        			</div> 
        			
                    <div class="input-group">
                		<label for="name">Content:</label>
        		        <textarea class="form-control" rows="10" cols="82" id="content" name="content" style="resize:none; width: 100%;"></textarea>     
                    </div>
                    
                    <?php if($message != '') {?>
                    <div>
                        <?php echo $message; ?>
                    </div>
                    <?php } ?>	
        			<br/>
        			<div class="input-group">
        			<button type="submit" class="btn btn-default">Submit</button>
        			</div>
        			
        		</form>
            </div>
        </div>
    </div>

</div>