<div class="jumbotron">
    <img alt="" src="/img/top.jpg" style="width: 100%">
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <b>Chart House - Seafood with a Perfect View</b>
                </p>
                <p>
                    For more than 50 years, Chart House has redefined the ideal dining experience. 
                    With 28 waterfront and showcase locations ranging from the historic to the unforgettable, 
                    Chart House restaurants specialize in dazzling views, unique cuisine and exceptional service. 
                </p>
                <p>
                    From fresh fish specialties to succulent steaks, the renowned chefs of Chart House have tailored a menu 
                    that adds a unique touch to local flavors.
                </p>
                
                <button class="btn btn-default" onclick="parent.location='/agent/home'">Bacome Publisher Now</button>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
            </div>
            <div class="panel-body">
                <img alt="" src="/img/statistics.png" style="width:100%">
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <div class="video-container">
                <iframe width="100%" height="200px" src="https://www.youtube.com/embed/GdTYC812EJ4?rel=0"></iframe>
                </div>
                
                <p>
                    <b>Chart House - Seafood with a Perfect View</b>
                </p>
                <p>
                    For more than 50 years, Chart House has redefined the ideal dining experience. 
                    With 28 waterfront and showcase locations ranging from the historic to the unforgettable, 
                    Chart House restaurants specialize in dazzling views, unique cuisine and exceptional service. 
                </p>
                
             </div>
        </div>
    </div>
</div>