<?php

?>

        <div class="row">
        
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('Careers') ?></h3>
                    </div>
                    <div class="panel-body">

                        
                            The Landry's culture motivates employees to achieve their full potential. They're challenged to improve 
                            through leadership, focus, intensity and persistence — and to create a work environment of pride, honesty, 
                            integrity and loyalty. Innovative training programs designed to strengthen the Company's management foundation 
                            also encourage employees toward career growth.
                            
                            In addition to owning and operating hotels, casinos and entertainment complexes, 
                            Landry's Inc. is one of the largest full-service restaurant operators in the United States with over 480 locations 
                            in 40 states and 15 countries. We operate restaurants primarily under the names of Rainforest Cafe, Saltgrass Steakhouse, 
                            Morton's – The Steakhouse, McCormick &amp; Schmick's, 
                            Landry's Seafood House, The Chart House, Oceanaire, Bubba Gump, and Claim Jumper, 
                            plus our upscale signature group of restaurants which includes Vic &amp; Anthony's. 
                            We are also engaged in the ownership and operation of select hospitality/entertainment 
                            businesses and casinos including The Golden Nugget casinos, The Kemah Boardwalk and the Historic 
                            Galveston Island Pleasure Pier. We need high caliber, experienced individuals to join our organization. 
                            If your skills and talents are a match for our needs, we can open the door to career opportunities!
                            Corporate Office Positions
                            Restaurant Management Opportunities
                            Casino Opportunities
                            Restaurant &amp; Hospitality Staff Positions
                        
                    </div>
                </div>
            </div>
        </div>
  