<div class="row">
    <div class="col-sm-8">
    
        <div class="row">
        
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('The Challenge.') ?></h3>
                    </div>
                    <div class="panel-body">

                        <p>
                            Dashboards promise to solve a host of business problems,
                            and they do as long as they're spotlighting the right numbers.
                            But sometimes the most important metrics are the hardest to measure,
                            and the complications don't stop there:
                        </p>
                    
                        <ul>
                    		<li>Integrating new data sources is time-intensive</li>
                    		<li>Building and modifying visualizations can be overwhelming</li>
                    		<li>Getting everyone access to the same data is a hassle</li>
                    	</ul>                    
                    
                    </div>
                </div>
            </div>
        </div>
    		
        <div class="row">
        
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('The Solution.') ?></h3>
                    </div>
                    <div class="panel-body">
                    	<p>
                        	Domo is more than a dashboard it's a single platform to run your entire business.
                        	What you need is a solution that brings people and information together.
                        	A single place where decisions are made with confidence.
                        	With Domo's business management platform, you can:
                    	</p>
                    	<ul>
                    		<li>Connect: Instantly connect to 100s of data sources without any coding or IT</li>
                    		<li>Prepare Transform data easily with simple drag and drop actions</li>
                    		<li>Visualize: Create intuitive, dynamic visualizations in just minutes</li>
                    		<li>Engage: Collaborate right where the data lives with Twitter-like functionality</li>
                    		<li>Optimize: Give everyone not just data analysts the ability to make better decisions</li>
                    	</ul>
                    </div>
                </div>
            </div>
        </div>
    
    </div>

</div>