

<div class="row">
    <div class="col-sm-8">
    
        <div class="row">
        
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('The Challenge.') ?></h3>
                    </div>
                    <div class="panel-body">

                        <p>
                            Dashboards promise to solve a host of business problems,
                            and they do as long as they're spotlighting the right numbers.
                            But sometimes the most important metrics are the hardest to measure,
                            and the complications don't stop there:
                        </p>
                    
                        <ul>
                    		<li>Integrating new data sources is time-intensive</li>
                    		<li>Building and modifying visualizations can be overwhelming</li>
                    		<li>Getting everyone access to the same data is a hassle</li>
                    	</ul>                    
                    
                    </div>
                </div>
            </div>
        </div>
    		
        <div class="row">
        
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('The Solution.') ?></h3>
                    </div>
                    <div class="panel-body">
                    	<p>
                        	Domo is more than a dashboard it's a single platform to run your entire business.
                        	What you need is a solution that brings people and information together.
                        	A single place where decisions are made with confidence.
                        	With Domo's business management platform, you can:
                    	</p>
                    	<ul>
                    		<li>Connect: Instantly connect to 100s of data sources without any coding or IT</li>
                    		<li>Prepare Transform data easily with simple drag and drop actions</li>
                    		<li>Visualize: Create intuitive, dynamic visualizations in just minutes</li>
                    		<li>Engage: Collaborate right where the data lives with Twitter-like functionality</li>
                    		<li>Optimize: Give everyone not just data analysts the ability to make better decisions</li>
                    	</ul>
                    </div>
                </div>
            </div>
        </div>
         					
    
        <div class="row">
        
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo $this->translate('Seafood with a Perfect View') ?></h3>
                    </div>
                    <div class="panel-body">

                        <div class="video-container">
                            <iframe width="100%" height="300px" src="https://www.youtube.com/embed/GdTYC812EJ4?rel=0"></iframe>
                        </div>
                        
                        <div class="video-container">
                        
                            <p>
                                <b>Chart House - Seafood with a Perfect View</b>
                            </p>
                            <p>
                                For more than 50 years, Chart House has redefined the ideal dining experience. 
                                With 28 waterfront and showcase locations ranging from the historic to the unforgettable, 
                                Chart House restaurants specialize in dazzling views, unique cuisine and exceptional service. 
                            </p>  
                        </div>
                                    
                    </div>
                </div>
            </div>
        </div>
    	  	
    					
    </div>
    
    <div class="col-sm-4" style="background-color:#6495ED">
    
        <h2>Registration Form</h2>
    		<form role="form">
        		<div class="form-group">
    				<label for="name">Restaurant Name:</label>
    				<input type="number" class="form-control" id="name" placeholder="Enter restaurant name">
    			</div>

    			<div class="form-group">
    				<label for="name">Email:</label>
    				<input type="email" class="form-control" id="email" placeholder="Enter email">
    			</div>
    			
    			<div class="form-group">
    				<label for="name">Phone:</label>
    				<input type="tel" class="form-control" id="phone" placeholder="Enter phone number">
    			</div>    			    			
    			
    			<hr/>
    			
    			<div class="form-group">
    				<label for="name">City:</label>
    				<input type="text" class="form-control" id="city" placeholder="Enter city">
    			</div>
    			
     			<div class="form-group">
    				<label for="name">State:</label>
    				<input type="text" class="form-control" id="state" placeholder="Enter state">
    			</div>

     			<div class="form-group">
    				<label for="name">Country:</label>
    				<input type="text" class="form-control" id="country" value="US">
    			</div>
    			    			
    			<button type="submit" class="btn btn-default">Submit</button>
    		</form>
    	   <br/>
    </div>

</div>
