<?php
?>

<div id="main"><div class="container">
	<article id="content">


<h1>Our Story</h1>

<div class="heroimage floatright withmargin"><img src="http://www.chart-house.com/img/our-story.jpg" alt="Photo of the original Chart House restaurant" /></div>
<p>For more than five decades, Chart House patrons have been treated to extraordinary cuisine and spectacular views. From the humble beginnings of our first restaurant in Aspen, Colorado, to the opening of our 28th location inside Golden Nugget Atlantic City, Chart House has developed a nationwide reputation for excellence.</p>
<p>The Chart House concept was born on Independence Day in 1961, the brainchild of famed Hawaiian surfer Joey Cabell and U.S. Navy man Buzzy Bent. The first location was modest, with just a few tables in a converted diner. However, two principles present in 1961 remain staples of every Chart House location &ndash; great food and equally impressive views. In 2012, for the third year in a row, OpenTable released a list of the 100 restaurants with the most scenic views. Chart House dominated the list, accounting for 10 of the 100. Today, Chart House restaurants overlook the coasts of both the Atlantic and the Pacific, and other scenic locations in between. And while we stretch from sea to shining sea, every location remains committed and specialized to its local community.</p>
<p>Whether you choose to dine at our location 750 feet above San Antonio in the Tower of the Americas, at our Cardiff by the Sea restaurant with the surf breaking right at your table or at our Weehawken location with breathtaking views of the Manhattan skyline, you can't go wrong with one of our signature fish specialties, slow-roasted prime rib and delicious salads. Our original Hot Lava Chocolate Cake is the perfect end to a memorable dining experience at Chart House.</p>
<p>We hope you make the decision to dine with us soon, and become a part of the Chart House legend &ndash; more than 50 years in the making.</p>


		<div class="spacer"></div>
	</article><!-- /#content -->
</div><!-- /.container --></div><!-- /#main -->