<?php

$title = 'Resource';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

 <ul>
    <li>
     <a href="/system/role">Role</a>
    </li>
    
    <li>
     <a href="/system/resource">Resource</a>
    </li>
    
    <li>
     <a href="/system/permission">Permission</a>
    </li>
</ul>
 
 
 <table class="table">
 <tr>
     <th>ID</th>
     <th>Name</th>
     <th>&nbsp;</th>
 </tr>
 
 <?php foreach ($resources as $resouce) : ?>
 <tr>
 <td><?php echo $this->escapeHtml($resouce->id);?></td>
     <td><?php echo $this->escapeHtml($resouce->resource_name);?></td>
     <td>
         <a href="<?php echo $this->url('system',
             array('action'=>'edit', 'id' => $resouce->id));?>">Edit</a>
         <a href="<?php echo $this->url('system',
             array('action'=>'delete', 'id' => $resouce->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
  
</table>
